config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resources :categories

  resources :products  do
    collection do
      get 'test'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :body, presence: true
  validates :price, numericality: true

  belongs_to :category

  def category_name
    if self.category.nil?
      "No registra"
    else
      self.category.name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  after_action :prepare_unobtrusive_flash
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :body)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end


  def show
  end


  def new
    @product = Product.new
    respond_to do |format|
      format.js
      format.html
    end
  end


  def edit
  end


  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def test
    @products = Product.pluck(:price)

    render json: @products
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :body, :price, :date, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # def ajax_flash(div_id)
  #   response = ""
  #   flash_div = ""
  #
  #   flash.each do |name, msg|
  #     if msg.is_a?(String)
  #       flash_div = "<div class=\"ui #{name == :notice ? 'success' : 'error'} message ajax_flash\"><i class=\"close icon\"></i><div class=\"header\" id=\"flash_#{name == :notice ? 'notice' : 'error'}\">#{h(msg)}</div></div>"
  #     end
  #   end
  #
  #   response = "$('.ajax_flash').remove();$('#{div_id}').prepend('#{flash_div}');"
  #   response.html_safe
  # end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, html: {class: "ui form"}) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <%= f.input_field :name %>
  </div>

  <div class="field">
    <%= f.input_field :body %>
  </div>

  <div class="field">
    <%= f.button :submit, class: "ui green button" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="ui selectable celled stripped table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Acitons</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= sanitize category.name %></td>
        <td><%= sanitize category.body %></td>
        <td>
          <%= link_to 'Show', category, class: "ui button" %>
          <%= link_to 'Edit', edit_category_path(category), class: "ui teal button" %>
          <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red button" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class: "ui green button" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>
<br>
<%= link_to 'Back', categories_path, class: "ui button" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @category.body %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SemanticTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui fixed huge main menu">
      <div class="ui container">
        <div class="header item">
          <img class="logo" src="<%= image_path('diamond.svg') %>" alt="Logo">
        </div>
        <div class="item">
          <%= link_to "Categories", categories_path %>
        </div>
        <div class="item">
          <%= link_to "Products", products_path %>
        </div>
      </div>
    </div>
    <div class="ui container" id="top-div">
      <%= yield %>
    </div>
    <div id="modal-container"></div>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for(product, local: true, html: { class: 'ui form' }) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.input_field :name, id: :product_name %>
    <%= form.full_error :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.input_field :body, id: :product_body %>
    <%= form.full_error :body %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.input_field :price, id: :product_price %>
    <%= form.full_error :price %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.input_field :date, as: :string, id: :product_date %>
    <%= form.full_error :dates %>
  </div>
  <div class="field">
    <%= form.label :category %>
    <%= form.input_field :category_id, collection: Category.all, prompt: "Choose a category" %>
    <%= form.full_error :category %>
  </div>

  <div class="actions">
    <%= form.button :submit, nil, class: "ui green button" %>
  </div>
<% end %>

app/views/products/_modal.html.erb
<div class="ui modal">
  <div class="header">Create Product</div>
  <div class="content">
    <%= simple_form_for(@product, remote: true, local: true, html: { class: 'ui form' }) do |form| %>

      <div class="field">
        <%= form.label :name %>
        <%= form.input_field :name, id: :product_name %>
        <%= form.full_error :name %>
      </div>

      <div class="field">
        <%= form.label :body %>
        <%= form.input_field :body, id: :product_body %>
        <%= form.full_error :body %>
      </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.input_field :price, id: :product_price %>
        <%= form.full_error :price %>
      </div>

      <div class="field">
        <%= form.label :date %>
        <%= form.input_field :date, as: :string, id: :product_date %>
        <%= form.full_error :dates %>
      </div>

      <div class="field">
        <%= form.label :category %>
        <%= form.input_field :category_id, collection: Category.all, prompt: "Choose a category" %>
        <%= form.full_error :category %>
      </div>

      <div class="field">
        <div class="ui cancel button">Cancel</div>
        <%= form.button :submit, nil, class: "ui approve green button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<tr id="product_<%= product.id %>">
  <td><%= sanitize product.name %></td>
  <td><%= sanitize product.body %></td>
  <td><%= number_to_currency product.price %></td>
  <td><%= product.date %></td>
  <td><%= product.category_name %></td>
  <td>
    <%= link_to 'Show', product, class: "ui button" %>
    <%= link_to 'Edit', edit_product_path(product), class: "ui teal button" %>
    <%= link_to 'Destroy', product, remote: :true, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red button" %>
  </td>
</tr>

app/views/products/create.js.erb
$('.ui.modal').modal({
  transition: 'fly down'
}).modal('hide');

$("#products_container").append('<%= j render @product %>');

UnobtrusiveFlash.showFlashMessage("Producto creado correctamente.", {type: 'notice', timeout: 3000})

app/views/products/destroy.js.erb
$("#product_<%= @product.id %>").transition('fly left')

UnobtrusiveFlash.showFlashMessage("Product was successfully destroyed.", {type: 'notice', timeout: 3000})

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>
<br>
<%= link_to 'Show', @product, class: "ui red button" %> 
<%= link_to 'Back', products_path, class: "ui button" %>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="ui celled striped selectable table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Price</th>
      <th>Date</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody id="products_container">
    <%= render partial: 'product', collection: @products %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: "ui green button" %>
<%= link_to 'New Product AJAX Modal', new_product_path, remote: true, class: "ui black button" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>
<br>
<%= link_to 'Back', products_path, class: "ui button" %>

app/views/products/new.js.erb
$("#modal-container").html('<%= j render "modal" %>')

$('.ui.modal').modal({
  transition: 'fly down'
}).modal('show');

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= sanitize @product.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= sanitize @product.body %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Date:</strong>
  <%= @product.date %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>